"""add canada_wage table

Revision ID: b50fca14ac66
Revises: 
Create Date: 2026-01-13 17:02:41.296508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b50fca14ac66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canada_wages',
        sa.Column('noc_code', sa.String(length=10), nullable=False),
        sa.Column('noc_title_en', sa.String(length=255), nullable=False),
        sa.Column('noc_title_fr', sa.String(length=255), nullable=False),
        sa.Column('province', sa.String(length=10), nullable=False),
        sa.Column('er_code', sa.String(length=20), nullable=True),
        sa.Column('er_name_en', sa.String(length=255), nullable=True),
        sa.Column('er_name_fr', sa.String(length=255), nullable=True),
        sa.Column('low_wage', sa.Integer(), nullable=True),
        sa.Column('median_wage', sa.Integer(), nullable=True),
        sa.Column('high_wage', sa.Integer(), nullable=True),
        sa.Column('average_wage', sa.Integer(), nullable=True),
        sa.Column('quartile1_wage', sa.Integer(), nullable=True),
        sa.Column('quartile3_wage', sa.Integer(), nullable=True),
        sa.Column('annual_wage_flag', sa.Boolean(), nullable=False),
        sa.Column('source_2025', sa.String(length=255), nullable=True),
        sa.Column('data_source_en', sa.String(length=255), nullable=True),
        sa.Column('data_source_fr', sa.String(length=255), nullable=True),
        sa.Column('reference_period', sa.String(length=20), nullable=True),
        sa.Column('revision_date', sa.Date(), nullable=True),
        sa.Column('wage_comment_en', sa.Text(), nullable=True),
        sa.Column('wage_comment_fr', sa.Text(), nullable=True),
        sa.Column('non_wage_benefit_pct', sa.Float(), nullable=True),
        sa.Column('content_en', sa.Text(), nullable=True),
        sa.Column('content_fr', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('mdate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wages_er_code', 'canada_wages', ['er_code'], unique=False)
    op.create_index('idx_wages_noc_code', 'canada_wages', ['noc_code'], unique=False)
    op.create_index('idx_wages_noc_prov', 'canada_wages', ['noc_code', 'province'], unique=False)
    op.create_index('idx_wages_province', 'canada_wages', ['province'], unique=False)
    op.create_index('idx_wages_reference_period', 'canada_wages', ['reference_period'], unique=False)
    op.create_index(op.f('ix_canada_wages_id'), 'canada_wages', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('date', postgresql.TIMESTAMP(timezone=True, precision=6), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index('idx_reports_source', table_name='reports')
    op.drop_index('idx_reports_mdate', table_name='reports')
    op.drop_index('idx_reports_lead_owner', table_name='reports')
    op.drop_index('idx_reports_last_name', table_name='reports')
    op.drop_index('idx_reports_first_name', table_name='reports')
    op.drop_index('idx_reports_deal_stage', table_name='reports')
    op.drop_index('idx_reports_company', table_name='reports')
    op.drop_index('idx_reports_account_id', table_name='reports')
    op.create_index(op.f('ix_reports_id_copy1'), 'reports', ['id'], unique=False)
    op.create_index(op.f('idx_reports_source_copy1'), 'reports', ['source'], unique=False)
    op.create_index(op.f('idx_reports_mdate_copy1'), 'reports', ['mdate'], unique=False)
    op.create_index(op.f('idx_reports_lead_owner_copy1'), 'reports', ['lead_owner'], unique=False)
    op.create_index(op.f('idx_reports_last_name_copy1'), 'reports', ['last_name'], unique=False)
    op.create_index(op.f('idx_reports_first_name_copy1'), 'reports', ['first_name'], unique=False)
    op.create_index(op.f('idx_reports_deal_stage_copy1'), 'reports', ['deal_stage'], unique=False)
    op.create_index(op.f('idx_reports_company_copy1'), 'reports', ['company'], unique=False)
    op.create_index(op.f('idx_reports_account_id_copy1'), 'reports', ['account_id'], unique=False)
    op.add_column('innov', sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_innov_id'), table_name='innov')
    op.create_index(op.f('ix_reports_id'), 'innov', ['id'], unique=False)
    op.create_table('hs_pgvector_documents',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('blob_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blob_mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hs_pgvector_documents_pkey'))
    )
    op.create_index(op.f('hs_pgvector_kw_idx_01'), 'hs_pgvector_documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_table('absenteeism',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason_for_absence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_of_absence', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_the_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seasons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transportation_expense', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_from_residence_to_work', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('work_load_average_day_', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hit_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disciplinary_failure', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('son', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_drinker', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('social_smoker', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pet', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body_mass_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('absenteeism_time_in_hours', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mdate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('haystack_documents_copy1',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('blob_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blob_mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('haystack_documents_copy1_pkey'))
    )
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('haystack_documents',
    sa.Column('id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob_data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('blob_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('blob_mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('haystack_documents_pkey'))
    )
    op.create_index(op.f('haystack_keyword_index'), 'haystack_documents', [sa.literal_column("to_tsvector('english'::regconfig, content)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('haystack_hnsw_index'), 'haystack_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mdate', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_users_group_id_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_canada_wages_id'), table_name='canada_wages')
    op.drop_index('idx_wages_reference_period', table_name='canada_wages')
    op.drop_index('idx_wages_province', table_name='canada_wages')
    op.drop_index('idx_wages_noc_prov', table_name='canada_wages')
    op.drop_index('idx_wages_noc_code', table_name='canada_wages')
    op.drop_index('idx_wages_er_code', table_name='canada_wages')
    op.drop_table('canada_wages')
    # ### end Alembic commands ###
